# global context
[build]
  publish = "public"
  command = "gulp"
# build a preview (optional)
[context.deploy-preview]
  command = "gulp preview"
# build a branch with debug (optional)
[context.branch-deploy]
  command = "gulp debug"
